services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    command: yarn run start:prod
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - MODE_DEBUG=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAILTRAP_USERNAME=${MAILTRAP_USERNAME}
      - MAILTRAP_PASSWORD=${MAILTRAP_PASSWORD}